# Generated by Django 4.1.1 on 2022-09-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('fact', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_stars', models.IntegerField()),
                ('animal_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalfacts.animalfact')),
            ],
        ),
        migrations.AddField(
            model_name='animalfact',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalfacts.breed'),
        ),
    ]
