# Generated by Django 4.1.1 on 2022-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalfacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfact',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
